config/routes.rb
Rails.application.routes.draw do
  resources :stat_lines
  resources :players
    resources :stat_entries
    resources :stats
    resources :games
    resources :teams
    resources :divisions
    resources :conferences
    resources :leagues

    get 'stats/:id/calculate_all' => 'stats#calculate_all'
    get 'stats/:id/export' => 'stats#export'
    get 'teams/:id/export' => 'teams#export'

    get 'games/update_games' => 'games#update_games'

end

app/models/conference.rb
class Conference < ActiveRecord::Base
  belongs_to :league
  has_many :divisions
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
    before_action :set_conference, only: [:show, :edit, :update, :destroy]

    # GET /conferences
    # GET /conferences.json
    def index
        @conferences = Conference.all
    end

    # GET /conferences/1
    # GET /conferences/1.json
    def show
    end

    # GET /conferences/new
    def new
        @leagues = League.all
        @conference = Conference.new
    end

    # GET /conferences/1/edit
    def edit
        @leagues = League.all
    end

    # POST /conferences
    # POST /conferences.json
    def create
        @leagues = League.all
        @conference = Conference.new(conference_params)

        respond_to do |format|
            if @conference.save
                format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
                format.json { render :show, status: :created, location: @conference }
            else
                format.html { render :new }
                format.json { render json: @conference.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /conferences/1
    # PATCH/PUT /conferences/1.json
    def update
        respond_to do |format|
            if @conference.update(conference_params)
                format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
                format.json { render :show, status: :ok, location: @conference }
            else
                format.html { render :edit }
                format.json { render json: @conference.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /conferences/1
    # DELETE /conferences/1.json
    def destroy
        @conference.destroy
        respond_to do |format|
            format.html { redirect_to conferences_url, notice: 'Conference was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
        @conference = Conference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
        params.require(:conference).permit(:name, :league_id)
    end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
    <% if @conference.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

            <ul>
                <% @conference.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :league %><br>
        <%= f.collection_select :league_id, @leagues, :id, :name %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/conferences/edit.html.erb
<h1>Editing Conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/index.html.erb
<div class="row">
    <div class="small-12 columns">
        <p id="notice"><%= notice %></p>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <h1>Listing Conferences</h1>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>League</th>
                    <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <% @conferences.each do |conference| %>
                    <tr>
                        <td><%= link_to conference.name, conference %></td>
                        <td><%= link_to conference.league.name, conference.league %></td>
                        <td><%= link_to 'Show', conference %></td>
                        <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
                        <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

<br>

<div class="row">
    <div class="small-12 columns">
        <%= link_to 'New Conference', new_conference_path %>
    </div>
</div>

app/views/conferences/new.html.erb
<h1>New Conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

app/views/conferences/show.html.erb
<div class="row">
    <div class="small-12 columns">
        <p id="notice"><%= notice %></p>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <h1><%= @conference.name %></h1>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <table>
            <th>Divisions</th>
            <% @conference.divisions.each do |division| %>
                <tr>
                    <td><%= link_to division.name, division %></td>
                </tr>
            <% end %>
        </table>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <%= link_to 'Edit', edit_conference_path(@conference) %> |
        <%= link_to 'Back', conferences_path %>
    </div>
</div>