config/routes.rb
Rails.application.routes.draw do
  resources :stat_lines
  resources :players
    resources :stat_entries
    resources :stats
    resources :games
    resources :teams
    resources :divisions
    resources :conferences
    resources :leagues

    get 'stats/:id/calculate_all' => 'stats#calculate_all'
    get 'stats/:id/export' => 'stats#export'
    get 'teams/:id/export' => 'teams#export'

    get 'games/update_games' => 'games#update_games'

end

app/models/division.rb
class Division < ActiveRecord::Base
  belongs_to :conference
  has_many :teams
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
    before_action :set_division, only: [:show, :edit, :update, :destroy]

    # GET /divisions
    # GET /divisions.json
    def index
        @divisions = Division.all
    end

    # GET /divisions/1
    # GET /divisions/1.json
    def show
    end

    # GET /divisions/new
    def new
        @conferences = Conference.all
        @division = Division.new
    end

    # GET /divisions/1/edit
    def edit
        @conferences = Conference.all
    end

    # POST /divisions
    # POST /divisions.json
    def create
        @conferences = Conference.all
        @division = Division.new(division_params)

        respond_to do |format|
            if @division.save
                format.html { redirect_to @division, notice: 'Division was successfully created.' }
                format.json { render :show, status: :created, location: @division }
            else
                format.html { render :new }
                format.json { render json: @division.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /divisions/1
    # PATCH/PUT /divisions/1.json
    def update
        respond_to do |format|
            if @division.update(division_params)
                format.html { redirect_to @division, notice: 'Division was successfully updated.' }
                format.json { render :show, status: :ok, location: @division }
            else
                format.html { render :edit }
                format.json { render json: @division.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /divisions/1
    # DELETE /divisions/1.json
    def destroy
        @division.destroy
        respond_to do |format|
            format.html { redirect_to divisions_url, notice: 'Division was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_division
        @division = Division.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def division_params
        params.require(:division).permit(:name, :conference_id)
    end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.erb
<%= form_for(@division) do |f| %>
    <% if @division.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@division.errors.count, "error") %> prohibited this division from being saved:</h2>

            <ul>
                <% @division.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :conference %><br>
        <%= f.collection_select :conference_id, @conferences, :id, :name %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing Division</h1>

<%= render 'form' %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

app/views/divisions/index.html.erb
<div class="row">
<div class="small-12 columns">
    <p id="notice"><%= notice %></p>
</div>
</div>

<div class="row">
    <div class="small-12 columns">
        <h1>Listing Divisions</h1>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Conference</th>
                    <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <% @divisions.each do |division| %>
                    <tr>
                        <td><%= link_to division.name, division %></td>
                        <td><%= link_to division.conference.name, division.conference %></td>
                        <td><%= link_to 'Show', division %></td>
                        <td><%= link_to 'Edit', edit_division_path(division) %></td>
                        <td><%= link_to 'Destroy', division, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

<br>

<div class="row">
    <div class="small-12 columns">
        <%= link_to 'New Division', new_division_path %>
    </div>
</div>

app/views/divisions/new.html.erb
<h1>New Division</h1>

<%= render 'form' %>

<%= link_to 'Back', divisions_path %>

app/views/divisions/show.html.erb
<div class="row">
    <div class="small-12 columns">
        <p id="notice"><%= notice %></p>
    </div>
</div>


<div class="row">
    <div class="small-12 columns">
        <h1><%= @division.name %></h1>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <table>
            <th>Teams</th>
            <% @division.teams.each do |team| %>
                <tr>
                    <td><%= link_to team.name, team %></td>
                </tr>
            <% end %>
        </table>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <%= link_to 'Edit', edit_division_path(@division) %> |
        <%= link_to 'Back', divisions_path %>
    </div>
</div>