config/routes.rb
Rails.application.routes.draw do
  resources :stat_lines
  resources :players
    resources :stat_entries
    resources :stats
    resources :games
    resources :teams
    resources :divisions
    resources :conferences
    resources :leagues

    get 'stats/:id/calculate_all' => 'stats#calculate_all'
    get 'stats/:id/export' => 'stats#export'
    get 'teams/:id/export' => 'teams#export'

    get 'games/update_games' => 'games#update_games'

end

app/models/stat.rb
class Stat < ActiveRecord::Base
    has_many :stat_entries
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
    before_action :set_stat, only: [:show, :edit, :update, :destroy, :calculate_all, :export]

    # GET /stats
    # GET /stats.json
    def index
        @stats = Stat.all
    end

    # GET /stats/1
    # GET /stats/1.json
    def show
        win_prediction
    end

    # GET /stats/new
    def new
        @compare_columns = Game.column_names
        @stat = Stat.new
    end

    # GET /stats/1/edit
    def edit
        @compare_columns = Game.column_names
    end

    # GET /stats/1/calculate_all
    def calculate_all
        # first, delete all stat entries for this stat
        StatEntry.where(stat_id: @stat.id).each do |stat_entry|
            stat_entry.delete
        end

        # create week 0 stat entries
        Team.all.each do |team|
            rating = Rating.new(1500, rand(348..352), 0.06)
            first_year = Game.order(:year).first.year
            stat_entry = StatEntry.new(week: 0, year: first_year, team_id: team.id, stat_id: @stat.id, rating: rating[:rating], rating_deviation: rating[:rating_deviation], volatility: rating[:volatility])
            stat_entry.save
        end

        # create all other entries
        games = Game.where("#{@stat.home_compare_field} >= 0").order(:year, :week)
        games.each do |game|
            if game[@stat.home_compare_field] > game[@stat.away_compare_field]
                winner = Team.where(short_name: game.home_team)[0]
                loser = Team.where(short_name: game.away_team)[0]
            else
                winner = Team.where(short_name: game.away_team)[0]
                loser = Team.where(short_name: game.home_team)[0]
            end

            winner_stat = StatEntry.where(stat_id: @stat.id, team_id: winner.id).order(:year).order(:week).last
            loser_stat = StatEntry.where(stat_id: @stat.id, team_id: loser.id).order(:year).order(:week).last

            winner_rating = Rating.new(winner_stat.rating, winner_stat.rating_deviation, winner_stat.volatility)
            loser_rating = Rating.new(loser_stat.rating, loser_stat.rating_deviation, loser_stat.volatility)

            period = Glicko2::RatingPeriod.from_objs([winner_rating, loser_rating])
            period.game([winner_rating, loser_rating], [1, 2])
            next_period = period.generate_next
            next_period.players.each { |p| p.update_obj }

            new_winner_stat = StatEntry.new(week: game.week, year: game.year, team_id: winner.id, stat_id: @stat.id,
                                            rating: next_period.players[0].obj[:rating], rating_deviation: next_period.players[0].obj[:rating_deviation],
                                            volatility: next_period.players[0].obj[:volatility])
            new_loser_stat = StatEntry.new(week: game.week, year: game.year, team_id: loser.id, stat_id: @stat.id,
                                           rating: next_period.players[1].obj[:rating], rating_deviation: next_period.players[1].obj[:rating_deviation],
                                           volatility: next_period.players[1].obj[:volatility])

            new_winner_stat.save
            new_loser_stat.save
        end

        redirect_to @stat, notice: 'Stat Entries created.'
        return
    end

    def win_prediction
        @right_win_predictions = 0
        @right_line_predictions = 0
        @total_predictions = 0
        @games = Game.where.not('home_score' => nil).order(year: :asc, week: :asc)
        @games.each do |game|
            home_team = Team.where(short_name: game.home_team)[0]
            away_team = Team.where(short_name: game.away_team)[0]
            home_stat_entry = StatEntry.where(stat_id: @stat.id, year: game.year, week: game.week - 1, team_id: home_team.id).where.not('rating' => nil).first
            away_stat_entry = StatEntry.where(stat_id: @stat.id, year: game.year, week: game.week - 1, team_id: away_team.id).where.not('rating' => nil).first
            if home_stat_entry and away_stat_entry
                if home_stat_entry.rating - 2*home_stat_entry.rating_deviation > away_stat_entry.rating + 2*away_stat_entry.rating_deviation
                    if game.home_score > game.away_score
                        @right_win_predictions += 1
                    end
                    if game.home_ats_result == 'win'
                        @right_line_predictions += 1
                    end
                elsif away_stat_entry.rating - 2*away_stat_entry.rating_deviation > home_stat_entry.rating + 2*home_stat_entry.rating_deviation 
                    if game.away_score > game.home_score
                        @right_win_predictions += 1
                    end
                    if game.away_ats_result == 'win'
                        @right_line_predictions += 1
                    end
                end

                if home_stat_entry.rating - 2*home_stat_entry.rating_deviation > away_stat_entry.rating + 2*away_stat_entry.rating_deviation or
                    away_stat_entry.rating - 2*away_stat_entry.rating_deviation > home_stat_entry.rating + 2*home_stat_entry.rating_deviation
                    @total_predictions += 1
                end
            end
        end
        @stat.win_prediction = ((@right_win_predictions / @total_predictions.to_f) * 100).to_i if @total_predictions
        @stat.line_prediction = ((@right_line_predictions / @total_predictions.to_f) * 100).to_i if @total_predictions
        @stat.save
    end

    # GET /stats/1/export
    # show stat_diff | score_diff
    def export
        @entries = []
        lines = []
        lines << "Rating Diff,Score Diff"
        @games = Game.where('home_score >= 0')
        stat_entries = StatEntry.where(stat_id: @stat.id)
        @games.each do |game|
            home_team = Team.where(short_name: game.home_team)[0]
            away_team = Team.where(short_name: game.away_team)[0]

            home_stat_entry = StatEntry.where(stat_id: @stat.id, week: game.week-1, year: game.year, team_id: home_team.id)[0]
            away_stat_entry = StatEntry.where(stat_id: @stat.id, week: game.week-1, year: game.year, team_id: away_team.id)[0]

            if home_stat_entry and away_stat_entry
                if home_stat_entry.rating
                    if home_stat_entry.rating - 2*home_stat_entry.rating_deviation > away_stat_entry.rating + 2*away_stat_entry.rating_deviation
                        lines << "#{home_stat_entry.rating - away_stat_entry.rating},#{game.home_score - game.away_score}"
                    end
                    if away_stat_entry.rating - 2*away_stat_entry.rating_deviation > home_stat_entry.rating + 2*home_stat_entry.rating_deviation
                        lines << "#{away_stat_entry.rating - home_stat_entry.rating},#{game.away_score - game.home_score}"
                    end
                end
            end
        end

        csv_string = lines.join("\n")

        respond_to do |format|
            format.html { render :export }
            format.json { render json: @entries }
            format.csv { send_data(csv_string, :filename => "#{@stat.name.camelize}.csv", :type => "text/csv") }
        end

    end



    # POST /stats
    # POST /stats.json
    def create
        @compare_columns = Game.column_names
        @stat = Stat.new(stat_params)

        respond_to do |format|
            if @stat.save
                format.html { redirect_to @stat, notice: 'Stat was successfully created.' }
                format.json { render :show, status: :created, location: @stat }
            else
                format.html { render :new }
                format.json { render json: @stat.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /stats/1
    # PATCH/PUT /stats/1.json
    def update
        @compare_columns = Game.column_names
        respond_to do |format|
            if @stat.update(stat_params)
                format.html { redirect_to @stat, notice: 'Stat was successfully updated.' }
                format.json { render :show, status: :ok, location: @stat }
            else
                format.html { render :edit }
                format.json { render json: @stat.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /stats/1
    # DELETE /stats/1.json
    def destroy
        @stat.destroy
        respond_to do |format|
            format.html { redirect_to stats_url, notice: 'Stat was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_stat
        @stat = Stat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stat_params
        params.require(:stat).permit(:name, :predictive_power, :compare_field_a, :compare_field_b, :home_compare_field, :away_compare_field)
    end

end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/_form.html.erb
<%= form_for(@stat) do |f| %>
    <% if @stat.errors.any? %>
        <div class="row">
            <div class="small-12 columns">
                <div id="error_explanation">
                    <h2><%= pluralize(@stat.errors.count, "error") %> prohibited this stat from being saved:</h2>

                    <ul>
                        <% @stat.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    <% end %>

    <div class="row">
        <div class="small-12 columns">
            <div class="field">
                <%= f.label :name %><br>
                <%= f.text_field :name %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <div class="field">
                <%= f.label :home_compare_field %>
                <%= f.collection_select :home_compare_field, @compare_columns, :to_s, :to_s %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <div class="field">
                <%= f.label :away_compare_field %>
                <%= f.collection_select :away_compare_field, @compare_columns, :to_s, :to_s %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <div class="field">
                <%= f.label :predictive_power %><br>
                <%= f.text_field :predictive_power %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <div class="actions">
                <%= f.submit %>
            </div>
        </div>
    </div>
<% end %>

app/views/stats/edit.html.erb
<div class="row">
    <div class="small-12 columns">
        <h1>Editing Stat</h1>
    </div>
</div>

<%= render 'form' %>

<div class="row">
    <div class="small-12 columns">
        <%= link_to 'Show', @stat %> |
        <%= link_to 'Back', stats_path %>
    </div>
</div>

app/views/stats/index.html.erb
<div class="row">
    <div class="small-12 columns">
        <p id="notice"><%= notice %></p>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <h1>Stats</h1>
    </div>
</div>


<div class="row">
    <div class="small-12 columns">
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Home Compare Field</th>
                    <th>Away Compare Field</th>
                    <th>Win Prediction</th>
                    <th>Line Prediction</th>
                    <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <% @stats.each do |stat| %>
                    <tr>
                        <td><%= stat.name %></td>
                        <td><%= stat.home_compare_field %></td>
                        <td><%= stat.away_compare_field %></td>
                        <td><%= stat.win_prediction %>%</td>
                        <td><%= stat.line_prediction %>%</td>
                        <td><%= link_to 'Show', stat %></td>
                        <td><%= link_to 'Edit', edit_stat_path(stat) %></td>
                        <td><%= link_to 'Destroy', stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>


<div class="row">
    <div class="small-12 columns">
        <%= link_to 'New Stat', new_stat_path %>
    </div>
</div>

app/views/stats/new.html.erb
<h1>New Stat</h1>

<%= render 'form' %>

<%= link_to 'Back', stats_path %>

app/views/stats/show.html.erb
<div class="row">
    <div class="small-12 columns">
        <p id="notice"><%= notice %></p>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <h1><%= @stat.name %></h1>
    </div>
</div>


<div class="row">
    <div class="small-12 columns">
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Home Compare Field</th>
                    <th>Away Compare Field</th>
                    <th>Win Prediction</th>
                    <th>Line Prediction</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td><%= @stat.name %></td>
                    <td><%= @stat.home_compare_field %></td>
                    <td><%= @stat.away_compare_field %></td>
                    <td><%= @stat.win_prediction %>%</td>
                    <td><%= @stat.line_prediction %>%</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <%= link_to 'Calulate All', :controller => 'stats', :action => 'calculate_all', :id => @stat %> |
        <%= link_to 'Edit', edit_stat_path(@stat) %> |
        <%= link_to 'Back', stats_path %>
    </div>
</div>